import { mkdir, readdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';

const ID_CHARS = /^[A-Za-z0-9_-]+$/;

/** Stored label images: `<root>/<historyId>/<n>.png`. */
export class PrintStore {
  constructor(readonly root: string) {}

  private dir(historyId: string): string {
    // History ids are generated by us and validated at the route; guard against traversal anyway.
    if (!ID_CHARS.test(historyId)) throw new Error(`Invalid history id: ${historyId}`);
    return path.join(this.root, historyId);
  }

  async write(historyId: string, images: Uint8Array[]): Promise<void> {
    const dir = this.dir(historyId);
    await mkdir(dir, { recursive: true });
    await Promise.all(images.map((image, n) => writeFile(path.join(dir, `${n}.png`), image)));
  }

  async read(historyId: string, index: number): Promise<Buffer | null> {
    try {
      return await readFile(path.join(this.dir(historyId), `${index}.png`));
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw err;
    }
  }

  async readAll(historyId: string, count: number): Promise<Buffer[] | null> {
    const images: Buffer[] = [];
    for (let n = 0; n < count; n++) {
      const image = await this.read(historyId, n);
      if (!image) return null;
      images.push(image);
    }
    return images;
  }

  async remove(historyId: string): Promise<void> {
    await rm(this.dir(historyId), { recursive: true, force: true });
  }

  /** Directory names with their modification time. */
  async list(): Promise<Array<{ id: string; mtime: Date }>> {
    let names: string[];
    try {
      names = await readdir(this.root);
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return [];
      throw err;
    }
    const entries = await Promise.all(
      names.filter((name) => ID_CHARS.test(name)).map(async (name) => {
        const info = await stat(path.join(this.root, name)).catch(() => null);
        return info?.isDirectory() ? { id: name, mtime: info.mtime } : null;
      }),
    );
    return entries.filter((e): e is { id: string; mtime: Date } => e !== null);
  }
}
